<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Login | SGA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <!-- jQuery -->
        <script type="text/javascript" src="/js/jquery.js"></script>

        <!-- Bootstrap -->
        <link href="/library/bootstrap-3.3.4/css/bootstrap.css" rel="stylesheet" media="screen" />
        <script src="/library/bootstrap-3.3.4/js/bootstrap.js" type="text/javascript"></script>

        <link href="/css/style.css" rel="stylesheet" type="text/css" />
    </head>

    <body>

        <div class="box box-auth">

            <div class="divTitle" style="text-align: center;">Autenticação</div>
            <div class="box-conteudo">

                <?php

                use Safira\Message\FlashMessenger;

                if (FlashMessenger::hasMessage('msg')) {
                    echo FlashMessenger::getMessage('msg');
                }
                ?>
                
                <div style="text-align: center; margin-bottom: 20px;">
                    <img src="/img/topsys-m.png">
                </div>
                
                <br/>

                <form class="form-horizontal" method="post" action="/auth/login">
                    <div class="form-group">
                        <label for="login" class="col-sm-4 control-label">Usuário</label>
                        <div class="col-xs-4">
                            <input type="text" class="form-control" name="login" placeholder="Usuário">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="senha" class="col-sm-4 control-label">Senha</label>
                        <div class="col-xs-4">
                            <input type="password" class="form-control" name="senha" placeholder="Senha">
                        </div>
                    </div>
                    <div class="form-group">
                        <div style="text-align: center">
                            <button type="submit" class="btn btn-primary">Logar</button>
                        </div>
                    </div>
                </form>
                
            </div>

        </div>

    </body>
</html>







