<form class="form-horizontal" method="post" action="/usuario/add">
    <div class="form-group">
        <label for="nome" class="col-sm-2 control-label">Nome <span class="text-danger">*</span></label>
        <div class="col-sm-5">
            <input type="text" class="form-control" id="nome" name="nome" required="true" autocomplete="off" maxlength="120" onpaste="return false;" ondrop="return false;">
        </div>
    </div>
    <div class="form-group">
        <label for="login" class="col-sm-2 control-label">Login <span class="text-danger">*</span></label>
        <div class="col-sm-5">
            <input type="text" class="form-control" id="login" name="login" required="true" maxlength="45" autocomplete="off" onpaste="return false;" ondrop="return false;">
        </div>
    </div>
    <div class="form-group">
        <label for="senha" class="col-sm-2 control-label">Senha <span class="text-danger">*</span></label>
        <div class="col-sm-5">
            <input type="password" class="form-control" id="senha" name="senha" required="true" maxlength="45" autocomplete="off" onpaste="return false;" ondrop="return false;">
        </div>
    </div>
    <div class="form-group">
        <label for="perfil" class="col-sm-2 control-label">Perfil <span class="text-danger">*</span></label>
        <div class="col-sm-5">
            <select class="form-control" name="perfil" id="perfil" required="true">
                <option value="">-- Selecione --</option>
                <option value="1">Administrador</option>
                <option value="2">Usuário Comum</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a type="button" class="btn btn-danger" href="/usuario">Voltar</a>
        </div>
    </div>
</form>

<div class="col-sm-offset-2 divCamposObrigatorios">
    <span class="text-danger">*</span> Campos obrigatórios
</div>