<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $titlePage . " | SGA";?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
        <!-- jQuery -->
        <script type="text/javascript" src="/js/jquery.js"></script>

        <!-- Bootstrap -->
        <link href="/library/bootstrap-3.3.4/css/bootstrap.css" rel="stylesheet" media="screen" />
        <script src="/library/bootstrap-3.3.4/js/bootstrap.js" type="text/javascript"></script>
        
        <link href="/library/datetimepicker/datetimepicker.css" rel="stylesheet" media="screen" />
        <script src="/library/datetimepicker/bootstrap-datetimepicker.js" type="text/javascript"></script>
        
        <!-- Icones -->
        <link href="/fonts/font-awesome-4.3.0/css/font-awesome.css" rel="stylesheet" type="text/css" />

        <script src="/js/scripts.js" type="text/javascript"></script>
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
        
        <?php
        if (isset($styles)) {
            foreach ($styles as $style) {
                echo "<link rel='stylesheet' href='/css/{$style}'>";
            }
        }
        ?>

    </head>
    <body>

        <div class="box box-fluido">
            <div class="row">
                <span class="col-md-12"></span>
            </div>
            <div class="row">
                <span class="col-md-2">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="<?php if($controller == "atividade" && $action == "controleAtividade"){echo "active";} ?>"><a href="/atividade/controleAtividade">Controle de Atividades</a></li>
                        <li class="<?php if($controller == "atividade" && $action == "relatorio"){echo "active";} ?>"><a href="/atividade/relatorio">Relatório</a></li>
                        <?php
                        $userInfo = $_SESSION['userInfo'];
                        $idPerfil = $userInfo['perfil'];
                        if($idPerfil == 1):
                        ?>
                            <li class="<?php if(($controller == "atividade") && ($action == "index" || $action == "add" || $action == "edit" || $action == "delete")){echo "active";} ?>"><a href="/atividade">Cadastro de Atividades</a></li>

                            <li class="<?php if($controller == "projeto"){echo "active";} ?>"><a href="/projeto">Cadastro de Projetos</a></li>

                            <li class="<?php if($controller == "usuario"){echo "active";} ?>"><a href="/usuario">Cadastro de Usuários</a></li>
                        <?php endif; ?>
                       
                    </ul>
                    
                </span>
                <span class="col-md-10">
                    <div class="divTitle" style="text-align: center;"><?php echo $titlePage ?></div>
                    <div class="box-conteudo">
                        <?php

                        use Safira\Message\FlashMessenger;

                        if (FlashMessenger::hasMessage('msg')) {
                            echo FlashMessenger::getMessage('msg');
                        }
                        ?>
                        
                        <?php echo $this->content(); ?>
                        
                    </div>
                </span>
            </div>
        </div>

        <div class="box rodape-fixo">
            <span class="col-md-2"><b><?=$userInfo['nome']?></b></span>
            <span class="col-md-7"><b><center><img src="/img/topsys-p.png" style="padding-right: 20px;"> SGA - Sistema de Gerenciamento de Atividades</center></b></span>
            <span class="col-md-2"><b><?php if($userInfo['perfil'] == 1){echo "ADMINISTRADOR";} else {echo "USUÁRIO COMUM";}?></b></span>
            <span class="col-md-1"><a type="button" class="btn btn-warning" href="/auth/logout"><span class="fa fa-sign-out"></span> Sair</a></span>
        </div>
        
    </body>

    <?php
    if (isset($scripts)) {
        foreach ($scripts as $script) {
            echo "<script src='/js/{$script}'></script>";
        }
    }
    ?>

</html>
