<form class="form-horizontal" method="post" action="/atividade/edit/<?=$entity->getId()?>">
    <div class="hidden">
        <input class="hidden" type="hidden" name="id" value="<?=$entity->getId()?>"><br/>
    </div>
    <div class="form-group">
        <label for="projeto" class="col-sm-2 control-label">Projeto <span class="text-danger">*</span></label>
        <div class="col-sm-8">
            <select class="form-control" name="projeto" id="projeto" required="true">
                <option value="">-- Selecione --</option>
               
                <?php foreach ($objProjetos as $objPro) { ?>
                    <option <?php if($entity->getProjeto()->getId() == $objPro->getId()){echo "selected";} ?> value="<?=$objPro->getId();?>"><?=$objPro->getDescricao();?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="descricao" class="col-sm-2 control-label">Descrição <span class="text-danger">*</span></label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="descricao" name="descricao" value="<?= $entity->getDescricao(); ?>" maxlength="120" required="true" autocomplete="off" onpaste="return false;" ondrop="return false;">
        </div>
    </div>
    <div class="form-group">
        <label for="usuario" class="col-sm-2 control-label">Responsável <span class="text-danger">*</span></label>
        <div class="col-sm-8">
            <select class="form-control" name="usuario" id="usuario" required="true">
                <option value="">-- Selecione --</option>
                <?php foreach ($objResponsavel as $obj) { ?>
                    <option value="<?=$obj->getId();?>" <?php if($entity->getUsuario()->getId() == $obj->getId()){echo "selected";} ?>><?=$obj->getNome();?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="prazo" class="col-sm-2 control-label">Prazo <span class="text-danger">*</span></label>
        <div class="col-sm-3">
            <div class="input-group">
                <input type="number" min="0" class="form-control" id="prazo" name="prazo" value="<?= $entity->getPrazo(); ?>" maxlength="5" required="true" autocomplete="off" onpaste="return false;" ondrop="return false;">
                <span class="input-group-addon" id="sizing-addon2">horas</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="dataInicio" class="col-sm-2 control-label">Data Início <span class="text-danger">*</span></label>
        <div class="col-sm-3">
            <input type="text" class="form-control dataField" id="dataInicio" name="dataInicio" value="<?= $entity->getDataInicio()->format('d/m/Y H:i'); ?>" required="true" autocomplete="off" onpaste="return false;" ondrop="return false;">
        </div>
    </div>
    <div class="form-group">
        <label for="statusAtividade" class="col-sm-2 control-label">Status <span class="text-danger">*</span></label>
        <div class="col-sm-5">
            <select class="form-control" name="statusAtividade" id="statusAtividade" required="true">
                <option value="">-- Selecione --</option>
                <?php foreach ($objStatus as $objSt) { ?>
                    <option <?php if($entity->getStatusAtividade()->getId() == $objSt->getId()){echo "selected";} ?> value="<?=$objSt->getId();?>"><?=$objSt->getDescricao();?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Atualizar</button>
            <a type="button" class="btn btn-danger" href="/atividade">Voltar</a>
        </div>
    </div>
</form>

<div class="col-sm-offset-2 divCamposObrigatorios">
    <span class="text-danger">*</span> Campos obrigatórios
</div>